### ISSUE TITLE
启用服务之后，访问webcamera test站点无效

### ISSUE THREAD

**Issue by leapyear1969** [Sowevo/bjjnts#4]
启用服务之后，访问webcamera test站点无效，目前测试几个小时还没有出现人脸识别的情况。不知道能不能通过人脸识别。
我是Windows 10的机器，没有摄像头。请问访问web camera test站点是否需要安装虚拟摄像头？
![image](https://user-images.githubusercontent.com/18607988/144208783-cd1065e8-294f-4df2-b6b0-e9d5fa78e531.png)

![image](https://user-images.githubusercontent.com/18607988/144208598-5f64ff05-a5cb-4b3c-a5a0-ad18c3690b43.png)

**Comment by Sowevo** [comment]
[使用这个地址试一下效果](https://webrtc.github.io/samples/src/content/peerconnection/pc1/)

**Comment by Sowevo** [comment]
不需要额外的虚拟摄像头软件

**Comment by leapyear1969** [comment]
还是不行，报错如下：
![image](https://user-images.githubusercontent.com/18607988/144535288-184196d1-d14b-4855-a90c-c8309d6de915.png)

我检查了程序的checkFace()的方法，里面看起来是没有处理人脸识别这块，只是点击了一下。难道这个就是这样处理的？
目前我运行了几个小时，有计算的验证，这个是可以通过的。我还没有遇到人脸识别的验证，所以不确定是否有问题。

```java
    public void checkFace() {
        try {
            WebElement codeBtn = driver.findElement(By.cssSelector("button[class='ant-btn ant-btn-primary']"));
            codeBtn.click();
            log.info("人脸识别");
        } catch (Exception ignored) {}
    }
```

**Comment by Sowevo** [comment]
是不是文件位置不对?刚更新了代码,增加了对视频文件位置的检查

**Comment by leapyear1969** [comment]
非常感谢，通过视频文件的检查，发现是我的视频文件名称不对，我修改视频文件名为username之后就可以了。
`
